[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
remappings = [
  "@account-abstraction/contracts=lib/account-abstraction/contracts",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/contracts-upgradable=lib/openzeppelin-contracts-upgradable/contracts",
]
viaIR = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
wrap_comments = true
